bracketSpacing: true
plugins:
  - "prettier-plugin-solidity"
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "es5"

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.18"
      parser: "solidity-parse"
      tabWidth: 4
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
  - files: "hardhat.config.ts"
    options:
      importOrder: ["hardhat-diamond-abi", "<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
